### ISSUE TITLE
Docs isn't clear enough on how to run dsw

### ISSUE THREAD

**Issue by jaydson** [NascHQ/dsw#21]
> just run again the dsw command line on your project

I'm following the docs and then suddenly I get the instruction above.
I'm confused because at this step I never used the `dsw` command yet.

Also, I don't get yet why do we need the `dsw` globally :confused:

**Comment by felipenmoura** [comment]
Just added some better description on how to use dsw.

It is installed globally, so you can run and re-run it easily from whenever you are.
