### ISSUE TITLE
boilerplate directory isn't working

### ISSUE THREAD

**Issue by murielsilveira** [NascHQ/dsw#23]
``` bash
➜  dsw git:(master) git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'boilerplate'
➜  dsw git:(master)
```

maybe `.gitmodules` file is missing?

**Comment by felipenmoura** [comment]
Yes, you were right!
I realised it does not need to be a submodule and changed this in the "development" branch.
Pushed in commit 664fa32 to fix it.

**Comment by murielsilveira** [comment]
:metal:
