### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'transaction' of undefined

### ISSUE THREAD

**Issue by jaydson** [NascHQ/dsw#32]
I followed the documentation and I got this error in the console when I tried to run my `index.html` file.
I'm missing something?

Looking at the code, the error is related to IndexDB I think:

```
function getObjectStore(dbName) {
    var mode = arguments.length <= 1 || arguments[1] === undefined ? 'readwrite' : arguments[1];

    var db = dbs[dbName],
        tx = db.transaction(dbName, mode);
    return tx.objectStore(dbName);
}
```

**Comment by felipenmoura** [comment]
Commit 52ffb4ebdac1d20b87132cc4122d4a4a138f9e96 fixes it.
Thanks for reporting.
