### ISSUE TITLE
Critical dependency

### ISSUE THREAD

**Issue by fetchTe** [NascHQ/dsw#8]
Line [44](https://github.com/NascHQ/dsw/blob/3a4dcd532cb2ffc7ad011645e2a030d284f14c8a/lib/dsw.js#L44) `require(finalPath)` is a critical dependency. Not a huge issue but it will throw an error if users are using webpack.

**Comment by felipenmoura** [comment]
Hm, I see.
But in this case, that `require` is used only in a node environment. This file is called only via command line or from another require in the server side...so it can generate the service worker file.
You think it could become a problem under what situation?

**Comment by felipenmoura** [comment]
Closing this issue. This situation has been fixed.
If you know of any related problem, please comment here.

**Comment by fetchTe** [comment]
@felipenmoura, sorry I must have missed you response. Nevertheless, thanks!
